#include<stdio.h>

int main(){
    FILE *fptr;
    fptr= fopen("generated.txt", "a");
    fprintf(fptr, "Hello, this file is generated by C language file IO operations.\n");
    fclose(fptr);
    return 0;
}